"devops":
  - ".github/**/*"
  - "Dockerfile"
  - "*entrypoint.sh"
  - "Makefile"
"dependency":
  - "pyproject.toml"
  - "pdm.lock"
"documentation":
  - "docs/**/*"
  - "mkdocs.yml"
  - "README.md"
"version":
  - "fmtm_splitter/__version__.py"
