site_name: fmtm-splitter
site_description: A program for splitting a large AOI into smaller tasks.
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/fmtm-splitter"
repo_url: "https://github.com/hotosm/fmtm-splitter/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: images/favicon.png
  logo: images/hot_logo.png
  # custom_dir: docs/overrides

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - About: about.md
  - Usage: usage.md
  - API: api.md
  - Testing Visually: testing-visually.md
  - License: LICENSE.md
  - Code of Conduct: https://docs.hotosm.org/code-of-conduct
  - Changelog: CHANGELOG.md
  - Versioning: https://docs.hotosm.org/dev-guide/version-control/#creating-releases
