name: Build CI Img

on:
  # Push includes PR merge
  push:
    branches:
      - main
    paths:
      # Workflow is triggered only if deps change
      - "pyproject.toml"
      - "Dockerfile"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  extract-vars:
    uses: hotosm/gh-workflows/.github/workflows/py_app_version.yml@main
    with:
      package_name: fmtm_splitter

  backend-ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    needs: [extract-vars]
    with:
      build_target: ci
      image_tags: |
        "ghcr.io/hotosm/fmtm-splitter:${{ needs.extract-vars.outputs.app_version }}-ci"
        "ghcr.io/hotosm/fmtm-splitter:ci"
      build_args: |
        PKG_VERSION=${{ needs.extract-vars.outputs.app_version }}
